server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pltc
    username: root
    password: js3183!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

app:
  kakao:
    rest-key: "b3a7210b08c31124f59ac122283e0d3e"
    redirect-uri: "http://localhost:8080/auth/kakao/callback"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"

  jwt:
    secret: "q3P9f8nS1yX0aZ7kL4mB2vC6rT9uW3xY"
    access-token-expire-seconds: 259200


